const colors = {
  light: {
    text: "#2c3e50",
    tint: "#2ecc71",
    background: "#FFFFFF",
    foreground: "#2c3e50",
    card: "#f8fffe",
    cardForeground: "#2c3e50",
    primary: "#2ecc71",
    primaryForeground: "#ffffff",
    secondary: "#f0faf4",
    secondaryForeground: "#2c3e50",
    muted: "#f0faf4",
    mutedForeground: "#7f8c8d",
    accent: "#e8f8f0",
    accentForeground: "#2c3e50",
    destructive: "#e74c3c",
    destructiveForeground: "#ffffff",
    border: "#d5f5e3",
    input: "#e8f8f0",
  },
  dark: {
    text: "#ecf0f1",
    tint: "#2ecc71",
    background: "#1a2634",
    foreground: "#ecf0f1",
    card: "#223344",
    cardForeground: "#ecf0f1",
    primary: "#2ecc71",
    primaryForeground: "#ffffff",
    secondary: "#2c3e50",
    secondaryForeground: "#ecf0f1",
    muted: "#2c3e50",
    mutedForeground: "#95a5a6",
    accent: "#2c3e50",
    accentForeground: "#ecf0f1",
    destructive: "#e74c3c",
    destructiveForeground: "#ffffff",
    border: "#34495e",
    input: "#34495e",
  },
  radius: 30,
};

export default colors;
