const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#00BFFF",
    background: "#ffffff",
    foreground: "#0a0a0a",
    card: "#f9f9f9",
    cardForeground: "#0a0a0a",
    primary: "#00BFFF",
    primaryForeground: "#ffffff",
    secondary: "#f0f0f0",
    secondaryForeground: "#1a1a1a",
    muted: "#f0f0f0",
    mutedForeground: "#737373",
    accent: "#f0f0f0",
    accentForeground: "#1a1a1a",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e5e5e5",
    input: "#e5e5e5",
  },
  dark: {
    text: "#f5f5f5",
    tint: "#00BFFF",
    background: "#0a0a0a",
    foreground: "#f5f5f5",
    card: "#141414",
    cardForeground: "#f5f5f5",
    primary: "#00BFFF",
    primaryForeground: "#0a0a0a",
    secondary: "#1e1e1e",
    secondaryForeground: "#e5e5e5",
    muted: "#1e1e1e",
    mutedForeground: "#737373",
    accent: "#1e1e1e",
    accentForeground: "#e5e5e5",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2a2a2a",
    input: "#2a2a2a",
  },
  radius: 12,
};

export default colors;
